name: Deploy on Render

run-name: ${{ github.event.client_payload.git_commit_msg }}

on:
  repository_dispatch:
    types: [ deploy-render ]

concurrency:
  group: deploy-render

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      VERSION_URL: https://${{ vars.RENDER_CUSTOM_DOMAIN }}/version
    environment:
      name: duddu.dev
      url: ${{ env.VERSION_URL }}
    steps:
      - name: Invoke Render hook
        timeout-minutes: 1
        run: curl -fs https://api.render.com/deploy/${{ secrets.RENDER_PROJECT_ID }}?key=${{ secrets.RENDER_DEPLOY_KEY }} >/dev/null
      - name: Verify deployed version
        timeout-minutes: 5
        run: |
          while curl -fs ${{ env.VERSION_URL }} | grep "${{ github.event.client_payload.git_revision }}" &>/dev/null; [[ $? -ne 0 ]];
          do
            echo "Waiting for deployment..."
            sleep 10
          done
          echo
          echo "Version healthcheck succeded! Deployed revision: ${{ github.event.client_payload.git_revision }}"