name: Publish Docker image

on:
  push:
    branches: [ main ]

concurrency:
  group: publish-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    env:
      GIT_REV_SHORT:
      NPM_VERSION:
      NPM_DISPLAY_NAME:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true
      - name: Set npm environment variables
        run: |
          echo "GIT_REV_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "NPM_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV
          echo "NPM_DISPLAY_NAME=$(npm pkg get displayName | tr -d '"')" >> $GITHUB_ENV
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        id: qemu
        with:
          platforms: linux/arm64/v8,linux/amd64
      - name: Extract image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          sbom: true
          target: production
          build-args: |
            NPM_VERSION=${{ env.NPM_VERSION }}
            GIT_REV_SHORT=${{ env.GIT_REV_SHORT }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.NPM_VERSION }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.version=${{ env.NPM_VERSION }}
            org.opencontainers.image.description="${{ env.NPM_DISPLAY_NAME }} (${{ env.NPM_VERSION}} - ${{ env.GIT_REV_SHORT }})"
          annotations: |
            ${{ steps.meta.outputs.annotations }}
            org.opencontainers.image.version=${{ env.NPM_VERSION }}
            org.opencontainers.image.description="${{ env.NPM_DISPLAY_NAME }} (${{ env.NPM_VERSION}} - ${{ env.GIT_REV_SHORT }})"
          platforms: linux/arm64/v8,linux/amd64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-cache,mode=max
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - name: Run deploy on Render workflow
        env:
          GH_TOKEN: ${{ github.token }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dispatches \
            -f "event_type=deploy-render" \
            -F "client_payload[commit_message]=$COMMIT_MESSAGE" \
            -F "client_payload[git_rev_short]=$GIT_REV_SHORT"