name: Evaluate Release

on:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: semantic-release

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: |
          npm install -g npm @vercel/ncc
          npm clean-install --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
      - name: Run Build Docker image workflow
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GH_TOKEN: ${{ github.token }}
          HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          RELEASE_TAG=$(git describe --tags HEAD --candidates 0 || echo '')
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/dispatches \
            -f "event_type=docker-main" \
            -F "client_payload[docker_revision]=$([ -n "$RELEASE_TAG" ] && echo "$RELEASE_TAG" || echo '${{ github.sha }}')" \
            -F "client_payload[docker_run_name]=$([ -n "$RELEASE_TAG" ] && echo "release: v$RELEASE_TAG" || echo "$HEAD_COMMIT_MESSAGE")" \
            -F "client_payload[docker_ref_name]=$([ -n "$RELEASE_TAG" ] && echo "$RELEASE_TAG" || echo "$REF_NAME")" \
            -F "client_payload[docker_ref_type]=$([ -n "$RELEASE_TAG" ] && echo 'tag' || echo 'branch')"